# Generated by Django 4.0.4 on 2022-04-27 18:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=50, verbose_name='Manufacturer')),
                ('model', models.CharField(max_length=100, verbose_name='Model')),
                ('yearOfManufacture', models.IntegerField(verbose_name='Year of manufacture')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, verbose_name='Name Customer')),
                ('Email', models.EmailField(max_length=254, verbose_name='Email Customer')),
                ('Phone', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')], verbose_name='Phone Customer')),
                ('Address', models.CharField(max_length=100, verbose_name='Address Customer')),
                ('Birthdate', models.DateField(auto_now_add=True, verbose_name='Name Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50, verbose_name='Name user')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Name Customer')),
                ('amount', models.DecimalField(decimal_places=5, max_digits=11, verbose_name='Amount($)')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.car')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer'),
        ),
    ]
