# Generated by Django 4.0.4 on 2022-04-29 20:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Order date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='Birthdate',
            field=models.DateField(verbose_name='Birthdate Customer'),
        ),
    ]
