# Generated by Django 4.0.4 on 2022-04-29 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_order_order_date_alter_customer_birthdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_date',
        ),
    ]
