# Generated by Django 4.0.4 on 2022-05-03 18:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customer_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='manufacturer',
            new_name='Manufacturer',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='model',
            new_name='Model',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='owner',
            new_name='Owner',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='yearOfManufacture',
            new_name='YearOfManufacture',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='amount',
            new_name='Amount',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='car',
            new_name='Car',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='Status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='Date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='User',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='users.customer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='Email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.RegexValidator(regex='^[-\\w.]+@([A-z0-9][-A-z0-9]+\\.)+[A-z]{2,4}$')], verbose_name='Phone Customer'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Phone',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^(\\+\\d{1,3})?,?\\s?\\d{8,13}')], verbose_name='Phone Customer'),
        ),
    ]
