# Generated by Django 4.0.4 on 2022-05-03 18:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_manufacturer_car_manufacturer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.RegexValidator(regex='^[-\\w.]+@([A-z0-9][-A-z0-9]+\\.)+[A-z]{2,4}$')], verbose_name='Email Customer'),
        ),
    ]
